apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web
  namespace: simple-webpage
  labels:
    app: webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
        - name: web-server
          image: fgold/simple-webpage:1.0.3
          ports:
            - containerPort: 8080
          env:
            - name: STATUSCODE
              value: "200"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
